[package]
name = "sipmsg"
version = "0.1.6"
authors = ["Anatolii Kurotych <akurotych@gmail.com>"]
edition = "2018"
description = "SIP message parser"
license = "MIT"
keywords = ["sip", "parser", "no_std"]
repository = "https://github.com/armatusmiles/sipcore"
categories = ["no-std"]

[features]
default = ["std"]
std = ["nom/std"]

[dependencies.nom]
version = "^5"
default-features = false

[dependencies.unicase]
version ="^2.6"
default-features = false
